import type { Campaign, ScheduledPost, ThirdPartyConnection, CreativeSourceItem } from "./campaign-types.ts";
export const SEED_BRAND_ID = "brand_tku_zenclub";
export const SEED_TIME = Date.parse("2026-09-01T00:00:00+08:00");

export const DEFAULT_CAMPAIGNS: Campaign[] = [
  {
    id: "camp_floating_light_0924",
    name: "09/24 浮游禪光",
    type: "tea-party",
    date: "2026-09-24",
    time: "18:30 - 20:30",
    location: "淡江大學 學生活動中心 或 覺軒花園草坪",
    oneLiner: "在淡水微涼的九月夜，讓漂浮的思緒靠岸，點亮一盞只屬於你的安定心光。",
    description: "開學第三週，面對新環境、選課與人際適應，淡江禪學社邀請所有新生與在校生，透過靜心、三色光引導與溫暖熱茶，找回生活呼吸的節奏。",
    theme: "放鬆・光影・呼吸・安頓",
    studentPain: "開學人際壓力、淡水下雨潮濕引起的疲憊感、找不到專屬於自己的安靜時空",
    mainCta: "填表預約茶會席位（免費參加）",
    signupUrl: "https://forms.gle/tamkang-zen-club",
    coverImage: "/seed/beans.jpg",
    relatedAssetIds: ["asset_beans", "asset_cup"],
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 1,
    status: "upcoming",
  },
  {
    id: "camp_zen_life_routine",
    name: "日常禪：克難坡上的慢呼吸",
    type: "daily",
    date: "2026-10-08",
    time: "每週四 19:00 - 20:30",
    location: "淡江 B304 社課教室",
    oneLiner: "爬完克難坡喘口氣，給心靈一個不需要被評分的空間。",
    description: "社課每週主題探索，結合坐禪專注力、情緒覺察與生活對話。",
    theme: "生活禪・情緒調節・專注練習",
    studentPain: "期中考將近、專案堆積如山、常常覺得腦袋很吵停不下來",
    mainCta: "直接到場體驗或 IG 私訊",
    signupUrl: "https://instagram.com/tku_zenclub",
    coverImage: "/seed/cup.jpg",
    relatedAssetIds: ["asset_cup"],
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now() - 86400000 * 2,
    status: "upcoming",
  },
];

export const DEFAULT_SCHEDULED_POSTS: ScheduledPost[] = [
  {
    id: "post_001",
    campaignId: "camp_floating_light_0924",
    title: "最近是不是連休息都覺得有罪惡感？",
    contentType: "carousel",
    status: "scheduled",
    scheduledAt: "2026-09-18 20:00",
    hook: "最近是不是連休息都覺得有罪惡感？",
    caption: `開學第三週，待辦清單突然變長。\n好不容易坐下來滑手機，心裡卻一直在想明天要交的報告。\n\n其實你不是不夠努力，只是太久沒有好好深呼吸了。\n\n淡江禪學社 09/24（四）晚間「浮游禪光」迎新茶會。\n不說教、不用懂深奧佛學，只要帶上你想放空的心情來坐坐。\n\n時間：09/24 18:30 入場\n地點：淡江大學活動中心\n免費報名連結在主頁簡介。`,
    hashtags: ["#淡江禪學社", "#淡江大學", "#淡水生活", "#克難坡", "#大學生日常", "#情緒急救包", "#放慢步調"],
    cta: "點擊主頁連結報名茶會席次",
    visualDirection: "深藍與月夜淡青漸層，搭配淡江校園夜景剪影，主標字級醒目留白",
    slidesCount: 5,
    sourceKind: "brand-memory",
    sourceRef: "淡江禪學社 Brand Brain",
  },
  {
    id: "post_002",
    campaignId: "camp_floating_light_0924",
    title: "浮游禪光主視覺：來喝一杯安定的熱茶",
    contentType: "ig-post",
    status: "completed",
    scheduledAt: "2026-09-21 19:30",
    hook: "有時候我們需要的不是標準答案，只是一個安靜的晚上。",
    caption: `淡江的秋天，風開始變大。\n在宮燈教室漫步，或是走在大學城嘈雜的人群中，你有多久沒和自己好好對話？\n\n浮游禪光・茶會倒數 3 天。\n備有一人席與朋友席，歡迎邀室友一起來吹晚風、喝熱茶、體驗三色光禪定。\n\n名額有限，報名詳見限動與主頁連結。`,
    hashtags: ["#淡江大學", "#淡江禪學社", "#浮游禪光", "#茶會", "#淡水夜晚", "#心靈綠洲"],
    cta: "立即點主頁連結預約席位",
    visualDirection: "溫暖柔和的暖黃與抹茶綠，手捧溫熱茶杯特寫，光斑點綴",
    sourceKind: "google-drive",
    sourceRef: "Google Drive / 2025茶會紀錄照片",
  },
  {
    id: "post_003",
    campaignId: "camp_floating_light_0924",
    title: "Reels 企劃：淡江通勤生必看的 3 個呼吸減壓技巧",
    contentType: "reels",
    status: "idea",
    scheduledAt: "2026-09-23 18:00",
    hook: "在淡水捷運紅線人擠人的車廂裡，你都怎麼放鬆？",
    caption: `紅線搖搖晃晃 40 分鐘，站著也能靜心的小祕訣。\n1. 腳底感受重心落定\n2. 吐氣比吸氣長兩秒\n3. 閉目聆聽軌道規律聲\n明天 09/24 晚上，來活動中心現場體驗完整引導！`,
    hashtags: ["#淡江通勤日常", "#紅線捷運", "#淡江生活", "#淡江禪學社", "#日常減壓"],
    cta: "收藏這則短影音，搭車時打開練習",
    visualDirection: "淡水捷運窗景夕陽與車廂剪影，節奏放慢，配字呼吸指引",
    sourceKind: "ai-generated",
    sourceRef: "AI Reels Script Generator",
  },
  {
    id: "post_004",
    title: "淡江雨季生存指南：給在宿舍發呆的你",
    contentType: "story",
    status: "published",
    scheduledAt: "2026-09-15 12:00",
    publishedAt: "2026-09-15 12:00",
    hook: "淡水又下雨了，雨聲其實是最天然的白噪音。",
    caption: "今日互動：窗外雨聲很大時，你最想做什麼？ (A) 躺平睡覺 (B) 泡一杯熱可可 (C) 戴上耳機靜心",
    hashtags: ["#淡水日常", "#淡江下雨日常", "#淡江禪學社"],
    cta: "投票分享你的下雨心情",
    visualDirection: "透明水滴滑落玻璃窗，搭配龜龜撐傘手繪卡片",
    sourceKind: "canva",
    sourceRef: "Canva / 龜龜雨天日常插畫",
    insights: {
      reach: 1240,
      likes: 182,
      comments: 24,
      shares: 31,
      saves: 56,
      hookEffectiveness: "高共鳴，淡江下雨情境轉發率達 4.5%",
    },
  },
];

export const DEFAULT_CONNECTIONS: ThirdPartyConnection[] = [
  {
    id: "google-drive",
    name: "Google Drive 素材庫",
    status: "connected",
    accountName: "tamkang.zenclub@gmail.com",
    accountDetail: "資料夾：淡江禪學社雲端主資料庫 (文宣、茶會照片、歷屆企劃、龜龜手繪)",
    lastSyncedAt: Date.now() - 1000 * 60 * 18,
    itemCount: 142,
  },
  {
    id: "canva",
    name: "Canva 設計工作台",
    status: "connected",
    accountName: "TKU Zen Club Design Team",
    accountDetail: "共用團隊：淡江禪學社 IG/海報模板庫 (含三色光活動板型、招生傳單)",
    lastSyncedAt: Date.now() - 1000 * 60 * 42,
    itemCount: 38,
  },
  {
    id: "instagram",
    name: "Instagram 官方串接",
    status: "connected",
    accountName: "@tku_zenclub",
    accountDetail: "淡江大學禪學社官方 IG（已授權 Insights 與 Post 存取）",
    lastSyncedAt: Date.now() - 1000 * 60 * 8,
    itemCount: 86,
  },
];

export const DEFAULT_CREATIVE_SOURCES: CreativeSourceItem[] = [
  {
    id: "src_drive_01",
    source: "google-drive",
    title: "2025秋季草地茶會社員互動高清照片.jpg",
    subtitle: "Google Drive / 活動紀錄 / 2025茶會",
    thumbnailUrl: "/seed/cup.jpg",
    category: "活動照片",
    tags: ["茶會", "熱茶", "溫暖", "同學互動", "草坪"],
    date: "2025-10-14",
  },
  {
    id: "src_drive_02",
    source: "google-drive",
    title: "淡江禪學社吉祥物-安靜龜龜矢量圖.png",
    subtitle: "Google Drive / 品牌資產 / 吉祥物",
    thumbnailUrl: "/seed/nisshoku-mark.svg",
    category: "品牌元素",
    tags: ["龜龜", "吉祥物", "透明底", "插畫", "三色光"],
    date: "2025-08-20",
  },
  {
    id: "src_canva_01",
    source: "canva",
    title: "【Canva】浮游禪光 IG Carousel 5P 品牌母模板",
    subtitle: "Canva Design / IG Template / 2026版",
    thumbnailUrl: "/seed/beans.jpg",
    category: "Canva設計",
    tags: ["Carousel", "三色光", "留白", "克難坡", "深青漸層"],
    date: "2026-09-02",
  },
  {
    id: "src_canva_02",
    source: "canva",
    title: "【Canva】淡江迎新季文宣海報 A3 印刷檔",
    subtitle: "Canva Design / 海報",
    thumbnailUrl: "/seed/beans.jpg",
    category: "Canva海報",
    tags: ["招生活動", "茶會", "字級排版", "品牌色"],
    date: "2026-08-28",
  },
  {
    id: "src_ig_01",
    source: "instagram",
    title: "IG Post:「給常常在淡江感到孤獨的你」 (互動破千熱門貼文)",
    subtitle: "Instagram / @tku_zenclub / 貼文紀錄",
    thumbnailUrl: "/seed/cup.jpg",
    category: "IG歷史表現優異",
    tags: ["高互動", "情緒共鳴", "生活感", "淡水夕陽"],
    date: "2025-11-03",
    metrics: "觸及 3,420 | 收藏 289 | 分享 145",
  },
  {
    id: "src_ig_02",
    source: "instagram",
    title: "IG Carousel:「期中考前只要五分鐘的呼吸急救術」",
    subtitle: "Instagram / @tku_zenclub / 輪播貼文",
    thumbnailUrl: "/seed/beans.jpg",
    category: "IG歷史表現優異",
    tags: ["實用方法", "期中不焦慮", "專注力", "收藏高"],
    date: "2025-11-18",
    metrics: "觸及 4,180 | 收藏 412 | 分享 180",
  },
];
