import { emptyBoilerplate } from "./boilerplate";
import { migrateBrief, migratePlan, migratePlanVersions } from "./brief";
import { buildLayout } from "./layout";
import { DEFAULT_SHADOW } from "./layers";
import type { AssetMeta, BrandKit, Layer, LineLayer, Project } from "./types";

export const SEED_BRAND_ID = "brand_tkuzen";
export const SEED_PROJECT_ID = "proj_floating_light";
export const SEED_DRAFT_ID = "proj_welcome_tea";
export const SEED_LOGO_ID = "asset_club_mark";
export const SEED_CUP_ID = "asset_tea_night";
export const SEED_BEANS_ID = "asset_tamsui";
export const SEED_TURTLE_ID = "asset_turtle";
export const SEED_LIGHT_ID = "asset_trilight";
export const SEED_CAMPUS_ID = "asset_campus";

const SEED_TIME = Date.parse("2026-09-10T20:00:00+08:00");

export const SEED_ASSETS: AssetMeta[] = [
  seedAsset({
    id: SEED_LOGO_ID,
    name: "日食標誌",
    kind: "logo",
    category: "logo",
    mime: "image/svg+xml",
    width: 80,
    height: 80,
    tags: ["logo", "品牌", "龜龜", "三色光"],
    createdAt: SEED_TIME,
    updatedAt: SEED_TIME,
    seedSrc: "/seed/club-mark.svg",
    source: "seed",
    licenseNotes: "淡江大學禪學社自有標誌。",
    licenseOwner: "淡江大學禪學社",
    favorite: true,
    lastUsedAt: SEED_TIME,
    useCount: 2,
  },
  {
    id: SEED_CUP_ID,
    name: "手沖杯",
    kind: "image",
    category: "mascot",
    mime: "image/svg+xml",
    width: 1080,
    height: 1350,
    tags: ["龜龜", "吉祥物", "角色"],
    createdAt: SEED_TIME,
    updatedAt: SEED_TIME,
    seedSrc: "/seed/cup.jpg",
    source: "seed",
    licenseNotes: "社團角色，可作主視覺或貼圖。",
    licenseOwner: "淡江大學禪學社",
    favorite: true,
    lastUsedAt: SEED_TIME,
    useCount: 1,
  },
  {
    id: SEED_CUP_ID,
    name: "夜晚茶會",
    kind: "image",
    category: "photo",
    mime: "image/svg+xml",
    width: 1080,
    height: 1350,
    tags: ["茶會", "晚上", "同學互動"],
    createdAt: SEED_TIME,
    updatedAt: SEED_TIME,
    seedSrc: "/seed/tea-night.svg",
    source: "seed",
    licenseNotes: "風格參考，可換成現場照片。",
    licenseOwner: "淡江大學禪學社",
    favorite: true,
    lastUsedAt: SEED_TIME,
    useCount: 2,
  },
  {
    id: SEED_BEANS_ID,
    name: "淡水黃昏",
    kind: "image",
    category: "tamsui",
    mime: "image/svg+xml",
    width: 1080,
    height: 1350,
    tags: ["淡水", "黃昏", "河岸"],
    createdAt: SEED_TIME,
    updatedAt: SEED_TIME,
    seedSrc: "/seed/tamsui.svg",
    source: "seed",
    licenseNotes: "淡水生活感背景。",
    licenseOwner: "淡江大學禪學社",
    favorite: true,
    lastUsedAt: Date.parse("2026-09-12T10:00:00+08:00"),
    useCount: 1,
  },
  {
    id: SEED_LIGHT_ID,
    name: "三色光",
    kind: "image",
    category: "poster",
    mime: "image/svg+xml",
    width: 1080,
    height: 1350,
    tags: ["三色光", "浮游禪光", "夜晚", "主視覺"],
    createdAt: SEED_TIME,
    updatedAt: SEED_TIME,
    seedSrc: "/seed/trilight.svg",
    source: "seed",
    licenseNotes: "浮游禪光燈光記憶。",
    licenseOwner: "淡江大學禪學社",
    favorite: true,
    lastUsedAt: SEED_TIME,
    useCount: 1,
  },
  {
    id: SEED_CAMPUS_ID,
    name: "淡江校園",
    kind: "image",
    category: "campus",
    mime: "image/svg+xml",
    width: 1080,
    height: 1350,
    tags: ["校園", "淡江", "斜坡"],
    createdAt: SEED_TIME,
    updatedAt: SEED_TIME,
    seedSrc: "/seed/campus.svg",
    source: "seed",
    licenseNotes: "校園生活場景。",
    licenseOwner: "淡江大學禪學社",
    favorite: false,
    lastUsedAt: null,
    useCount: 0,
  },
];

export const SEED_BRAND: BrandKit = {
  id: SEED_BRAND_ID,
  name: "淡江大學禪學社",
  handle: "@tkuzen",
  website: "",
  voice: "像社團的人在發 IG。先生活，再活動。禪要說成安定、專注、喘口氣，不要一開始就宗教或說教。",
  doSay: "淡江學生、淡水晚上、坐好、找朋友來、時間地點、坐一下就好",
  dontSay: "誠摯邀請、宗教、玄學、開示、功德、限時瘋搶",
  forbiddenWords: ["誠摯邀請", "玄學", "開示", "功德", "錯過就沒有"],
  colors: [
    { id: "c1", hex: "#3F6F64", role: "primary", label: "苔綠" },
    { id: "c2", hex: "#5B6E8A", role: "secondary", label: "暮藍" },
    { id: "c3", hex: "#F4F1EA", role: "background", label: "沙色" },
    { id: "c4", hex: "#E8A060", role: "accent", label: "暖光" },
    { id: "c5", hex: "#1C2422", role: "ink", label: "墨" },
  ],
  fontDisplay: "Noto Sans TC",
  fontBody: "Noto Sans TC",
  logoAssetId: SEED_LOGO_ID,
  logos: [
    {
      id: "logo_nisshoku_primary",
      name: "主標誌",
      assetId: SEED_LOGO_ID,
      usage: "primary",
    },
    {
      id: "logo_nisshoku_mark",
      name: "圖標",
      assetId: SEED_LOGO_ID,
      usage: "mark",
    },
  ],
  slogans: ["坐一下就好。", "先被看見，再看到活動。"],
  ctas: ["晚上見", "找一個朋友來", "坐一下就好"],
  imageStyle: {
    mood: "空氣感、夜色、朋友、療癒，不要廟",
    lighting: "淡水黃昏、三色光、室內暖燈，避免硬閃與塑料感",
    paletteHint: "苔綠、沙色、暖光、暮藍、水色",
    composition: "留白給第一句 Hook，活動名不要壓過生活感",
    do: "同學側臉、茶、燈、龜龜、河岸、校園斜坡",
    dont: "香爐、金身、過宗教、過老氣、過 AI、滿版標語",
  },
  rules: {
    noCompetitorMarks: true,
    noWatermark: true,
    noLowRes: true,
    notes: "Logo 不壓臉。活動海報不要看起來像寺廟廣告。",
  },
  boilerplate: {
    ...emptyBoilerplate(),
    cta: "晚上見",
    disclaimer: "",
    hashtags: ["#淡江禪學社", "#淡江", "#淡水"],
    captionClose: "時間地點看報名。找一個朋友一起來也行。",
  },
  mascot: "龜龜",
  signatureLights: "三色光",
  likes: ["生活 Hook", "夜色", "留白", "同學真實感", "龜龜"],
  dislikes: ["誠摯邀請", "說教", "佛學名詞開場", "連續招生"],
  clubIntro: "淡江大學禪學社在淡水校園。給學生一個可以慢下來、整理自己的地方。不是要把禪變成宗教廣告。",
  updatedAt: SEED_TIME,
};

/* ------------------------------------------------------------------ */
/* 示範活動：浮游禪光                                                     */
/* ------------------------------------------------------------------ */

const copy = {
  eyebrow: "09 / 24",
  headline: "最近是不是\n很久沒坐好",
  subhead: "浮游禪光 · 淡水校園",
  body: "開學以後行程一直被填滿。這晚我們把燈放下來，坐一會兒就好。",
  cta: "晚上見",
  handle: "@tkuzen",
  caption:
    "最近是不是很久沒有好好坐下來？\n\n不是要你突然變得很懂禪。\n只是開學以後，行程一直被填滿，連休息都會有一點罪惡感。\n\n9/24 晚上，浮游禪光。\n淡水校園，把燈放下來，坐一會兒就好。\n時間地點看報名連結，找一個朋友一起過來也行。",
  hashtags: ["#淡江禪學社", "#浮游禪光", "#淡江", "#淡水", "#開學"],
  altText: "夜色裡三色光輕輕浮著，標題寫著最近是不是很久沒坐好。",
};

function stabilize(layers: Layer[], prefix: string): Layer[] {
  return layers.map((layer, index) => ({ ...layer, id: `${prefix}${index}` }));
}

export function createSeedProject(): Project {
  const now = SEED_TIME;
  const page1 = buildLayout("feed-portrait", copy, SEED_BRAND, "quote", {
    imageAssetId: SEED_LIGHT_ID,
  });
  page1.layers = stabilize(page1.layers, "seed_ly_");
  page1.role = "cover";
  page1.templateId = "quote";

  const page2 = buildLayout(
    "feed-portrait",
    {
      ...copy,
      eyebrow: "LIFE",
      headline: "連休息都\n有罪惡感？",
      subhead: "淡江學生的九月",
      body: "課表、迎新、捷運、報告。自由，但不一定比較快樂。",
      cta: "坐一下就好",
    },
    SEED_BRAND,
    "quote",
  );
  page2.layers = stabilize(page2.layers, "seed_p2_ly_");
  page2.role = "problem";
  page2.templateId = "quote";

  const page3 = buildLayout(
    "feed-portrait",
    {
      ...copy,
      eyebrow: "NIGHT",
      headline: "把燈\n放下來",
      subhead: "浮游禪光",
      body: "不是講座。是一個晚上，燈、風、可以坐著的地方。",
      cta: "晚上見",
    },
    SEED_BRAND,
    "editorial",
    { imageAssetId: SEED_LIGHT_ID },
  );
  const line: LineLayer = {
    id: "seed_p3_line",
    name: "分隔線",
    type: "line",
    x: 72,
    y: 820,
    w: 220,
    h: 32,
    rotation: 0,
    opacity: 1,
    locked: false,
    hidden: false,
    fromLayout: false,
    stroke: "#B85C38",
    strokeWidth: 3,
    shadow: { ...DEFAULT_SHADOW },
  };
  page3.layers = [...stabilize(page3.layers, "seed_p3_ly_"), line];
  page3.role = "detail";
  page3.templateId = "editorial";

  const page4 = buildLayout(
    "feed-portrait",
    {
      ...copy,
      eyebrow: "HERE",
      headline: "淡水校園\n走幾步就到",
      subhead: "9/24 晚上",
      body: "通勤的人可以算一下末班車。住宿的人，下山再回宿舍也行。",
      cta: "看時間地點",
    },
    SEED_BRAND,
    "product",
    { imageAssetId: SEED_CAMPUS_ID },
  );
  page4.layers = stabilize(page4.layers, "seed_p4_ly_");
  page4.role = "proof";
  page4.templateId = "product";

  const page5 = buildLayout(
    "feed-portrait",
    {
      ...copy,
      eyebrow: "NOW",
      headline: "晚上見",
      subhead: "9/24 · 淡江大學淡水校園",
      body: "報名在簡介。找一個朋友一起來也行。",
      cta: "晚上見",
    },
    SEED_BRAND,
    "offer",
  );
  page4.layers = stabilize(page4.layers, "seed_p4_ly_");
  page4.role = "cta";
  page4.templateId = "offer";

  const page6 = buildLayout(
    "feed-portrait",
    {
      ...copy,
      eyebrow: "NOTE",
      headline: "坐一下\n就好。",
      subhead: "淡江禪學社",
      body: "不用先懂禪。",
      cta: "晚上見",
    },
    SEED_BRAND,
    "quote",
  );
  page6.layers = stabilize(page6.layers, "seed_p6_ly_");
  page6.role = "close";
  page6.templateId = "quote";

  const slides = [page1, page2, page3, page4, page5, page6];

  const brief = migrateBrief({
    product: "浮游禪光夜燈體驗",
    eventName: "浮游禪光",
    schedule: "2026/09/24 晚上",
    location: "淡江大學淡水校園",
    offer: "找一個朋友一起來",
    audience: "淡江大學學生，尤其剛開學、覺得自己很滿的人",
    goal: "traffic",
    features: "夜燈、坐下來、三色光、不用先懂禪",
    style: "生活、空氣、淡水夜晚",
    notes: "Hook 先行。不要宗教開場。",
    deliverables: { post: true, story: true, carousel: true, reels: true, threads: true, line: true },
  });

  const plan = migratePlan({
    campaignName: "浮游禪光",
    concept: "先讓學生覺得『我最近是不是很久沒坐好』，再告訴他們 9/24 晚上校園裡有燈。",
    insight: "開學季的淡江學生不是缺少活動，是缺少一個不必表演的晚上。",
    hook: "最近是不是很久沒有好好坐下來？",
    visualTheme: "夜色、三色光、留白、空氣感。",
    visualDirection: "深色底、光點、大字 Hook，活動名放第二層。",
    templateId: "quote",
    colorMood: "暮藍、暖光、水色",
    eyebrow: copy.eyebrow,
    headline: copy.headline,
    subhead: "茉莉、佛手柑、蜂蜜尾韻。",
    body: copy.body,
    cta: copy.cta,
    captions: [
      { style: "學生版", text: copy.caption },
      { style: "短版", text: "最近是不是很久沒坐好？\n9/24 晚上，浮游禪光。坐一下就好。" },
    ],
    hashtags: copy.hashtags,
    storyBeats: ["很久沒坐好", "燈會自己亮", "9/24 淡水校園"],
    carouselPages: [
      {
        role: "cover",
        headline: copy.headline,
        subhead: "浮游禪光",
        body: copy.caption.split("\n")[0],
        cta: "晚上見",
        visualNote: "大字 Hook，光在背景。",
        templateId: "quote",
      },
      {
        role: "problem",
        headline: "連休息都\n有罪惡感？",
        subhead: "淡江的九月",
        body: "課表一直被填滿。",
        cta: "坐一下就好",
        visualNote: "生活，不要廟。",
        templateId: "quote",
      },
      {
        role: "detail",
        headline: "把燈\n放下來",
        subhead: "不是講座",
        body: "燈、風、可以坐著。",
        cta: "晚上見",
        visualNote: "三色光特寫。",
        templateId: "editorial",
      },
      {
        role: "proof",
        headline: "走幾步\n就到",
        subhead: "淡水校園",
        body: "通勤的人可以算末班車。",
        cta: "看時間地點",
        visualNote: "校園路徑。",
        templateId: "product",
      },
      {
        role: "cta",
        headline: "晚上見",
        subhead: "9/24 · 淡江大學淡水校園",
        body: "報名在簡介。",
        cta: "晚上見",
        visualNote: "只留資訊。",
        templateId: "offer",
      },
      {
        role: "close",
        headline: "坐一下\n就好。",
        subhead: "淡江禪學社",
        body: "不用先懂禪。",
        cta: "晚上見",
        visualNote: "可截圖。",
        templateId: "quote",
      },
    ],
    assetNeeds: [
      { kind: "photo", title: "夜燈現場", detail: "三色光、人的側影。", required: true },
      { kind: "logo", title: "社徽", detail: "淺底或小標。", required: true },
      { kind: "illustration", title: "龜龜", detail: "可作第二則或貼圖。", required: false },
    ],
    checklist: ["Hook 在第一句", "9/24 與地點有出現", "沒有誠摯邀請", "不太宗教", "CTA 可讀"],
    altText: copy.altText,
    qaNotes: ["不要用寺廟視覺", "活動名不要壓過第一句"],
    generatedAt: now,
    source: "live",
    threadsPost: "最近是不是很久沒有好好坐下來？\n\n9/24 晚上浮游禪光，淡水校園。不用先懂禪。",
    lineCopy: "【浮游禪光】9/24 晚上 淡江淡水校園\n最近很滿的話，來坐一下。",
    studentReview: {
      wouldStop: "第一句會停。像在講我。",
      understandable: "看得懂。不是術語。",
      tooReligious: "沒有。燈跟坐好而已。",
      tooSerious: "還好，偏安靜但不說教。",
      tooLiterary: "有一點文，但能接受。",
      tooAi: "沒有金句連發。",
      tooLong: "Carousel 可以，單張 Caption 剛好。",
      knowsWhat: "知道是晚上的燈、坐下來。",
      knowsWhenWhere: "9/24、淡水校園有寫。",
      wouldBringFriend: "可以。門檻低。",
      knowsSignup: "寫了報名在簡介，最好再放連結。",
      notes: ["報名方式再清楚一點。"],
      rewriteHook: "",
    },
  });

  return {
    id: SEED_PROJECT_ID,
    name: "浮游禪光 · Carousel",
    createdAt: now,
    updatedAt: now,
    brandId: SEED_BRAND_ID,
    templateId: "quote",
    activeFormatId: "feed-portrait",
    status: "done",
    brief,
    copy,
    plan,
    artboards: {
      "feed-portrait": page1,
    },
    slides: {
      "feed-portrait": slides,
    },
    slideIndex: 0,
    snapshots: [
      {
        id: "snap_seed_v1",
        name: "初稿 · 四頁輪播",
        createdAt: now,
        kind: "manual",
        formatId: "feed-portrait",
        slideIndex: 0,
        artboard: structuredClone(page1),
        pages: structuredClone(slides),
      },
    ],
    planVersions: migratePlanVersions(undefined, plan),
    exports: [],
    campaignId: "camp_floating_light",
    contentKind: "carousel",
    scheduledAt: Date.parse("2026-09-17T20:00:00+08:00"),
    publishedAt: null,
  };
}

export function createSeedDraft(): Project {
  const now = Date.parse("2026-09-12T10:00:00+08:00");
  const draftCopy = {
    eyebrow: "TEA",
    headline: "開學茶會",
    subhead: "來坐一下，不用先懂禪。",
    body: "",
    cta: "找一個朋友來",
    handle: "@tkuzen",
    caption: "",
    hashtags: ["#日食咖啡"],
    altText: "",
  };
  const artboard = buildLayout("story", draftCopy, SEED_BRAND, "offer", {
    imageAssetId: SEED_CUP_ID,
  });
  artboard.layers = artboard.layers.map((layer, index) => ({
    ...layer,
    id: `seed_draft_ly_${index}`,
  }));
  return {
    id: SEED_DRAFT_ID,
    name: "開學茶會 · Story",
    createdAt: now,
    updatedAt: now,
    brandId: SEED_BRAND_ID,
    templateId: "quote",
    activeFormatId: "story",
    status: "creating",
    brief: migrateBrief({
      product: "開學茶會",
      eventName: "開學茶會",
      schedule: "開學後第一個晚上",
      location: "淡江大學淡水校園",
      offer: "找一個朋友來",
      audience: "大一新生與想認識人的舊生",
      goal: "ugc",
      features: "茶、坐下來、認識人",
      style: "輕、生活",
      notes: "草稿，標題層級未定。",
      deliverables: { post: false, story: true, carousel: false, reels: false, threads: false, line: true },
    }),
    copy: draftCopy,
    plan: null,
    artboards: {
      story: artboard,
    },
    slides: {
      story: [artboard],
    },
    slideIndex: 0,
    snapshots: [],
    planVersions: [],
    exports: [],
    campaignId: "camp_welcome_tea",
    contentKind: "story",
    scheduledAt: null,
    publishedAt: null,
  };
}

export const SEED_CONTENTS: ContentItem[] = [
  {
    id: "content_floating_kv",
    campaignId: SEED_CAMPAIGN_ID,
    type: "carousel",
    status: "done",
    title: "浮游禪光 · 主視覺輪播",
    copy: {
      tone: "normal",
      hook: copy.headline.replace("\n", ""),
      body: copy.caption.split("\n").slice(2).join("\n"),
      cta: copy.cta,
      hashtags: copy.hashtags,
    },
    variants: [],
    imagePrompt:
      "Tamkang University lantern-lined path at night, one warm lamp glowing, soft three-color glow (amber, teal, lavender), empty space in the lower third for text, photographic, film grain, no text, no religious symbols, Instagram 4:5",
    visualDirection: "夜晚宮燈大道的一盞燈，三色光暈，下方留白。",
    carousel: localCarousel(SEED_CAMPAIGN_CTX, seedCopyDraft),
    storyFrames: [],
    reels: [],
    threads: localThreads(SEED_CAMPAIGN_CTX, seedCopyDraft),
    line: localLine(SEED_CAMPAIGN_CTX, seedCopyDraft),
    review: null,
    sources: [
      { kind: "library", label: "素材庫 / 淡江 宮燈大道 夜", refId: SEED_CAMPUS_ID },
      { kind: "brand", label: "Brand Memory / 三色光、龜龜" },
    ],
    projectId: SEED_PROJECT_ID,
    coverAssetId: SEED_CAMPUS_ID,
    scheduledAt: Date.parse("2026-09-17T20:00:00+08:00"),
    publishedAt: null,
    metrics: null,
    createdAt: SEED_TIME,
    updatedAt: SEED_TIME,
    generatedBy: "live",
  },
  {
    id: "content_midterm_story",
    campaignId: null,
    type: "story",
    status: "drafting",
    title: "期中前 · 先給自己五分鐘",
    copy: {
      tone: "short",
      hook: "先給自己五分鐘",
      body: "報告寫到一半，突然不知道自己在幹嘛。\n週三晚上見。",
      cta: "週三晚上見",
      hashtags: ["#淡江大學禪學社"],
    },
    variants: [],
    imagePrompt: "",
    visualDirection: "三色光底 + 一行字",
    carousel: [],
    storyFrames: [],
    reels: [],
    threads: "",
    line: "",
    review: null,
    sources: [{ kind: "brand", label: "Brand Memory / 三色光" }],
    projectId: SEED_DRAFT_ID,
    coverAssetId: SEED_GLOW_ID,
    scheduledAt: null,
    publishedAt: null,
    metrics: null,
    createdAt: Date.parse("2026-09-12T10:00:00+08:00"),
    updatedAt: Date.parse("2026-09-12T10:00:00+08:00"),
    generatedBy: null,
  },
  {
    id: "content_welcome_recap",
    campaignId: null,
    type: "recap",
    status: "published",
    title: "迎新茶會 · 回顧",
    copy: {
      tone: "warm",
      hook: "謝謝昨天來的每一個人。",
      body: "有人是一個人來的，有人拉了室友。\n燈很暗，茶很熱，大家都沒有很會說話，但沒關係。\n下一次是 9/24 浮游禪光，一樣不用報名。",
      cta: "下次見",
      hashtags: ["#淡江大學禪學社", "#淡江", "#迎新", "#茶會"],
    },
    variants: [],
    imagePrompt: "",
    visualDirection: "現場照片三張 + 一句謝謝",
    carousel: [],
    storyFrames: [],
    reels: [],
    threads: "",
    line: "",
    review: null,
    sources: [{ kind: "instagram", label: "Instagram / 2026-09-11" }],
    projectId: null,
    coverAssetId: SEED_TAMSUI_ID,
    scheduledAt: Date.parse("2026-09-11T21:00:00+08:00"),
    publishedAt: Date.parse("2026-09-11T21:05:00+08:00"),
    metrics: { reach: 1260, likes: 143, comments: 12, saves: 31, shares: 18, views: 0, clicks: 22, syncedAt: SEED_TIME },
    createdAt: Date.parse("2026-09-11T20:00:00+08:00"),
    updatedAt: Date.parse("2026-09-11T21:05:00+08:00"),
    generatedBy: "live",
  },
  {
    id: "content_class_life",
    campaignId: null,
    type: "ig-post",
    status: "published",
    title: "週三社課 · 生活",
    copy: {
      tone: "life",
      hook: "宿舍很熱鬧，但你有點想安靜一下。",
      body: "每週三晚上，B302 燈會調暗一點。\n沒有點名，遲到也沒關係。坐著就好。",
      cta: "週三晚上見",
      hashtags: ["#淡江大學禪學社", "#淡江", "#社課", "#慢下來"],
    },
    variants: [],
    imagePrompt: "",
    visualDirection: "宿舍窗邊的一盞燈",
    carousel: [],
    storyFrames: [],
    reels: [],
    threads: "",
    line: "",
    review: null,
    sources: [{ kind: "instagram", label: "Instagram / 2026-09-03" }],
    projectId: null,
    coverAssetId: SEED_GLOW_ID,
    scheduledAt: Date.parse("2026-09-03T20:00:00+08:00"),
    publishedAt: Date.parse("2026-09-03T20:02:00+08:00"),
    metrics: { reach: 890, likes: 97, comments: 8, saves: 41, shares: 9, views: 0, clicks: 11, syncedAt: SEED_TIME },
    createdAt: Date.parse("2026-09-03T18:00:00+08:00"),
    updatedAt: Date.parse("2026-09-03T20:02:00+08:00"),
    generatedBy: "live",
  },
  {
    id: "content_knowledge_sit",
    campaignId: null,
    type: "knowledge",
    status: "published",
    title: "靜坐不是把腦清空",
    copy: {
      tone: "student",
      hook: "靜坐不是把腦清空。",
      body: "第一次來的人常問：我腦中一直在講話怎麼辦。\n可以講話。就讓它講。你只是先坐著。",
      cta: "",
      hashtags: ["#淡江大學禪學社", "#淡江", "#靜坐", "#第一次也可以"],
    },
    variants: [],
    imagePrompt: "",
    visualDirection: "留白 + 一行字",
    carousel: [],
    storyFrames: [],
    reels: [],
    threads: "",
    line: "",
    review: null,
    sources: [{ kind: "instagram", label: "Instagram / 2026-08-27" }],
    projectId: null,
    coverAssetId: SEED_MASCOT_ID,
    scheduledAt: Date.parse("2026-08-27T20:00:00+08:00"),
    publishedAt: Date.parse("2026-08-27T20:10:00+08:00"),
    metrics: { reach: 1540, likes: 188, comments: 21, saves: 76, shares: 24, views: 0, clicks: 6, syncedAt: SEED_TIME },
    createdAt: Date.parse("2026-08-27T12:00:00+08:00"),
    updatedAt: Date.parse("2026-08-27T20:10:00+08:00"),
    generatedBy: "live",
  },
  {
    id: "content_member_one",
    campaignId: null,
    type: "member-story",
    status: "published",
    title: "社員故事 · 大一",
    copy: {
      tone: "warm",
      hook: "我第一次來，是因為室友臨時不去。",
      body: "大一上，什麼社團都試過，都很吵。\n那天我一個人走到 B302，燈很暗，有人遞給我一杯茶。\n沒有人問我是哪一系的。",
      cta: "下次見",
      hashtags: ["#淡江大學禪學社", "#淡江", "#社員故事"],
    },
    variants: [],
    imagePrompt: "",
    visualDirection: "側臉或手的局部",
    carousel: [],
    storyFrames: [],
    reels: [],
    threads: "",
    line: "",
    review: null,
    sources: [{ kind: "instagram", label: "Instagram / 2026-08-20" }],
    projectId: null,
    coverAssetId: SEED_TAMSUI_ID,
    scheduledAt: Date.parse("2026-08-20T21:00:00+08:00"),
    publishedAt: Date.parse("2026-08-20T21:04:00+08:00"),
    metrics: { reach: 1102, likes: 164, comments: 19, saves: 52, shares: 31, views: 0, clicks: 14, syncedAt: SEED_TIME },
    createdAt: Date.parse("2026-08-20T16:00:00+08:00"),
    updatedAt: Date.parse("2026-08-20T21:04:00+08:00"),
    generatedBy: "live",
  },
  {
    id: "content_recruit_soft",
    campaignId: null,
    type: "ig-post",
    status: "published",
    title: "社博後 · 不是招生",
    copy: {
      tone: "humor",
      hook: "大學生活很自由，但你最近真的有比較快樂嗎？",
      body: "社博攤位很吵，我們攤位很安靜，有點對不起隔壁。\n如果你那天有拿走一杯茶，週三晚上還在。",
      cta: "直接來就好",
      hashtags: ["#淡江大學禪學社", "#淡江", "#社博", "#迎新"],
    },
    variants: [],
    imagePrompt: "",
    visualDirection: "攤位角落、龜龜",
    carousel: [],
    storyFrames: [],
    reels: [],
    threads: "",
    line: "",
    review: null,
    sources: [{ kind: "instagram", label: "Instagram / 2026-09-08" }],
    projectId: null,
    coverAssetId: SEED_CAMPUS_ID,
    scheduledAt: Date.parse("2026-09-08T19:30:00+08:00"),
    publishedAt: Date.parse("2026-09-08T19:35:00+08:00"),
    metrics: { reach: 2104, likes: 231, comments: 27, saves: 44, shares: 16, views: 0, clicks: 38, syncedAt: SEED_TIME },
    createdAt: Date.parse("2026-09-08T12:00:00+08:00"),
    updatedAt: Date.parse("2026-09-08T19:35:00+08:00"),
    generatedBy: "live",
  },
  {
    id: "content_floating_reels",
    campaignId: SEED_CAMPAIGN_ID,
    type: "reels",
    status: "drafting",
    title: "浮游禪光 · 20 秒 Reels",
    copy: {
      tone: "life",
      hook: "最近是不是很久沒有好好坐下來？",
      body: "9/24（三）19:00 B302，浮游禪光。燈調暗，坐墊放好。不用報名，直接來。",
      cta: "直接來就好",
      hashtags: ["#淡江大學禪學社", "#淡江", "#浮游禪光", "#慢下來"],
    },
    variants: [],
    imagePrompt:
      "Vertical 9:16 Instagram Reels cover of Tamkang University lantern-lined path at night, one warm lamp, soft three-color glow, tiny turtle mascot in the corner, no text, no watermark, no religious symbols",
    visualDirection: "前三秒質問字幕，中段社辦門口，結尾時間地點卡。",
    carousel: [],
    storyFrames: [],
    reels: [
      { from: 0, to: 3, visual: "手機畫面：凌晨 1:47，滑 IG。", caption: "最近是不是很久沒有好好坐下來？", voiceover: "", transition: "硬切", assetHint: "自拍手機畫面", assetId: null },
      { from: 3, to: 7, visual: "覺生圖書館空鏡，燈還亮著。", caption: "課表排滿了，人也認識了一些", voiceover: "有時候不是想睡，是停不下來。", transition: "慢推", assetHint: "校園夜景素材", assetId: SEED_CAMPUS_ID },
      { from: 7, to: 12, visual: "B302 門口，燈亮著，有人推門。", caption: "浮游禪光", voiceover: "有一個地方，去了不用做什麼。", transition: "跟拍", assetHint: "社辦 / 教室照片", assetId: null },
      { from: 12, to: 17, visual: "茶杯、坐墊、學生放鬆的側臉。", caption: "一個晚上，一杯茶", voiceover: "不用會打坐，不用信什麼。", transition: "疊化", assetHint: "歷屆活動照片", assetId: SEED_TAMSUI_ID },
      { from: 17, to: 20, visual: "純色卡：時間地點 + 龜龜。", caption: "9/24（三）19:00｜B302", voiceover: "直接來就好", transition: "定格", assetHint: "龜龜 + 三色光", assetId: SEED_MASCOT_ID },
    ],
    threads: "",
    line: "",
    review: null,
    sources: [
      { kind: "brand", label: "Brand Memory / 淡江禪學社" },
      { kind: "library", label: "素材庫 / 宮燈大道", refId: SEED_CAMPUS_ID },
    ],
    projectId: null,
    coverAssetId: SEED_CAMPUS_ID,
    scheduledAt: Date.parse("2026-09-21T20:00:00+08:00"),
    publishedAt: null,
    metrics: null,
    createdAt: SEED_TIME,
    updatedAt: SEED_TIME,
    generatedBy: "mock",
  },
  {
    id: "content_reels_stop",
    campaignId: null,
    type: "reels",
    status: "published",
    title: "先給自己五分鐘",
    copy: {
      tone: "short",
      hook: "先給自己五分鐘",
      body: "報告寫到一半，突然不知道自己在幹嘛。週三晚上，B302 燈會調暗一點。",
      cta: "週三晚上見",
      hashtags: ["#淡江大學禪學社", "#淡江", "#慢下來"],
    },
    variants: [],
    imagePrompt: "",
    visualDirection: "宿舍窗邊的一盞燈，9:16",
    carousel: [],
    storyFrames: [],
    reels: [
      { from: 0, to: 3, visual: "筆電螢幕，游標停在空白頁。", caption: "先給自己五分鐘", voiceover: "", transition: "硬切", assetHint: "宿舍桌面", assetId: null },
      { from: 3, to: 7, visual: "走廊很吵，門關上。", caption: "外面很熱鬧", voiceover: "", transition: "慢推", assetHint: "宿舍走廊", assetId: null },
      { from: 7, to: 12, visual: "三色光底，一行字。", caption: "坐著就好", voiceover: "不用會什麼。", transition: "疊化", assetHint: "三色光", assetId: SEED_GLOW_ID },
      { from: 12, to: 17, visual: "茶杯特寫。", caption: "週三晚上 B302", voiceover: "", transition: "跟拍", assetHint: "茶杯", assetId: null },
      { from: 17, to: 20, visual: "龜龜在角落。", caption: "一個人來也可以", voiceover: "週三晚上見", transition: "定格", assetHint: "龜龜", assetId: SEED_MASCOT_ID },
    ],
    threads: "",
    line: "",
    review: null,
    sources: [{ kind: "instagram", label: "Instagram / 2026-09-05" }],
    projectId: null,
    coverAssetId: SEED_GLOW_ID,
    scheduledAt: Date.parse("2026-09-05T21:00:00+08:00"),
    publishedAt: Date.parse("2026-09-05T21:04:00+08:00"),
    metrics: { reach: 980, likes: 76, comments: 9, saves: 48, shares: 22, views: 4120, clicks: 8, syncedAt: SEED_TIME },
    createdAt: Date.parse("2026-09-05T18:00:00+08:00"),
    updatedAt: Date.parse("2026-09-05T21:04:00+08:00"),
    generatedBy: "live",
  },
];

export const SEED_PROJECT = createSeedProject();
