import { CLUB_HANDLE, CLUB_NAME } from "./club.ts";
import type { ConnectionState, IgMemoryPost, MemoryItem } from "./types.ts";

export const SEED_CAMPAIGN_ID = "camp_floating_light";
export const SEED_TEA_ID = "camp_welcome_tea";

export const SEED_CONNECTIONS: ConnectionState[] = [
  {
    id: "drive",
    status: "disconnected",
    label: "Google Drive",
    detail: "指定禪學社資料夾後，AI 可搜尋照片、企劃與歷屆文宣。",
    lastSyncAt: null,
    accountName: null,
  },
  {
    id: "canva",
    status: "disconnected",
    label: "Canva",
    detail: "讀取海報、IG、Story 設計，作為風格參考或繼續編輯。",
    lastSyncAt: null,
    accountName: null,
  },
  {
    id: "instagram",
    status: "disconnected",
    label: "Instagram",
    detail: "官方 API 讀取粉專貼文、Carousel、Reels 與 Insights。",
    lastSyncAt: null,
    accountName: null,
  },
];

export const SEED_MEMORY: MemoryItem[] = [
  {
    id: "mem_drive_tea_2025",
    source: "drive",
    title: "2025 秋季茶會照片",
    subtitle: "Google Drive / 2025 茶會",
    thumbAssetId: "asset_tea_night",
    tags: ["茶會", "晚上", "同學互動", "淡水"],
    year: 2025,
    kind: "活動照片",
  },
  {
    id: "mem_drive_turtle",
    source: "drive",
    title: "龜龜角色與周邊",
    subtitle: "Google Drive / 品牌／龜龜",
    thumbAssetId: "asset_turtle",
    tags: ["龜龜", "吉祥物", "品牌"],
    year: 2024,
    kind: "Logo",
  },
  {
    id: "mem_drive_floating",
    source: "drive",
    title: "浮游禪光企劃與場地",
    subtitle: "Google Drive / 2025 浮游禪光",
    thumbAssetId: "asset_trilight",
    tags: ["浮游禪光", "三色光", "夜晚", "文宣"],
    year: 2025,
    kind: "活動企劃",
  },
  {
    id: "mem_canva_tea",
    source: "canva",
    title: "茶會主視覺模板",
    subtitle: "Canva / 茶會",
    thumbAssetId: "asset_tea_night",
    tags: ["茶會", "IG", "海報"],
    year: 2025,
    kind: "IG",
  },
  {
    id: "mem_canva_recruit",
    source: "canva",
    title: "招生活動版型",
    subtitle: "Canva / 招生",
    thumbAssetId: "asset_campus",
    tags: ["招生", "Story", "Carousel"],
    year: 2025,
    kind: "Template",
  },
  {
    id: "mem_canva_light",
    source: "canva",
    title: "三色光夜燈海報",
    subtitle: "Canva / 浮游禪光",
    thumbAssetId: "asset_trilight",
    tags: ["三色光", "浮游禪光", "海報"],
    year: 2025,
    kind: "海報",
  },
  {
    id: "mem_ig_sit",
    source: "instagram",
    title: "很久沒坐好",
    subtitle: "Instagram / 2025-09-18",
    thumbAssetId: "asset_tamsui",
    tags: ["情緒", "Hook", "生活"],
    year: 2025,
    kind: "IG Post",
  },
];

export const SEED_IG_POSTS: IgMemoryPost[] = [
  {
    id: "ig_20250918",
    mediaType: "image",
    caption:
      "最近是不是連休息都覺得有罪惡感？\n\n不是要你突然變得很懂禪。只是開學以後，行程一直被填滿。\n今晚淡水風有點涼，適合什麼都不做。",
    postedAt: Date.parse("2025-09-18T20:12:00+08:00"),
    assetId: "asset_tamsui",
    likes: 186,
    comments: 14,
    saves: 41,
    reach: 2400,
    hook: "最近是不是連休息都覺得有罪惡感？",
    analysis: "生活 Hook 先出現，活動資訊很少。學生停留高、收藏高。可作為情緒向 DNA。",
  },
  {
    id: "ig_20251002",
    mediaType: "carousel",
    caption:
      "有時候我們需要的不是答案，只是一個安靜的晚上。\n\n茶會不是考試。來坐一下、喝一杯，找一個朋友也行。",
    postedAt: Date.parse("2025-10-02T19:40:00+08:00"),
    assetId: "asset_tea_night",
    likes: 142,
    comments: 9,
    saves: 33,
    reach: 1980,
    hook: "有時候我們需要的不是答案，只是一個安靜的晚上。",
    analysis: "Carousel 封面是句子不是海報。中間頁講清楚時間地點後互動上升。",
  },
  {
    id: "ig_20251120",
    mediaType: "reels",
    caption: "淡水的晚上其實很適合什麼都不做。\n三色光、風、坐著的人。",
    postedAt: Date.parse("2025-11-20T21:05:00+08:00"),
    assetId: "asset_trilight",
    likes: 260,
    comments: 21,
    saves: 58,
    reach: 4100,
    hook: "淡水的晚上其實很適合什麼都不做。",
    analysis: "Reels 前 3 秒是河風與燈，不是社徽。完播較高。",
  },
  {
    id: "ig_20260312",
    mediaType: "image",
    caption: `${CLUB_NAME}本週社課\n時間地點見報名。`,
    postedAt: Date.parse("2026-03-12T18:00:00+08:00"),
    assetId: "asset_campus",
    likes: 37,
    comments: 1,
    saves: 4,
    reach: 620,
    hook: `${CLUB_NAME}本週社課`,
    analysis: "公告腔、太正式、沒有學生生活。觸及明顯較低。之後不要這樣開場。",
  },
  {
    id: "ig_20260408",
    mediaType: "carousel",
    caption: "大學生活很自由，但你最近真的有比較快樂嗎？\n\n龜龜也想問。來坐一下。",
    postedAt: Date.parse("2026-04-08T19:20:00+08:00"),
    assetId: "asset_turtle",
    likes: 171,
    comments: 18,
    saves: 39,
    reach: 2210,
    hook: "大學生活很自由，但你最近真的有比較快樂嗎？",
    analysis: "龜龜出鏡加學生口吻，留言多是「想帶室友來」。",
  },
  {
    id: "ig_20260501",
    mediaType: "image",
    caption: "剛到淡水的人，路線搞懂了嗎？搞不懂也沒關係，晚上我們在校園裡。",
    postedAt: Date.parse("2026-05-01T20:00:00+08:00"),
    assetId: "asset_campus",
    likes: 98,
    comments: 7,
    saves: 22,
    reach: 1540,
    hook: "剛到淡水的人，路線搞懂了嗎？",
    analysis: "對準新生與通勤生。地點清楚時收藏會上去。",
  },
];

export const IG_DNA = {
  handle: CLUB_HANDLE,
  colors: ["sage", "sand", "amber", "dusk", "mist"],
  events: ["茶會", "浮游禪光", "社課", "靜心", "招生"],
  voice: "像社團的人在發文。先生活，再活動。",
  captionLength: "短到中，前兩行必須是 Hook。",
  hashtags: ["#淡江禪學社", "#淡江", "#淡水", "#開學"],
  visual: "夜色、燈、茶、同學側臉、龜龜、留白。少廟、少香爐、少金身。",
  cta: ["晚上見", "找一個朋友來", "坐一下就好", "報名在簡介"],
  studentPref: "會停下來的是被說中的句子，不是活動海報。",
};
