/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ExportRouteImport } from './routes/export'
import { Route as InspireRouteImport } from './routes/inspire'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as CreateIndexRouteImport } from './routes/create.index'
import { Route as CreateImageRouteImport } from './routes/create.image'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioProjectIdRouteImport } from './routes/studio.$projectId'
import { Route as ApiIgMediaIdRouteImport } from './routes/api/ig-media.$id'
import { Route as ApiOauthCanvaCallbackRouteImport } from './routes/api/oauth.canva.callback'
import { Route as ApiOauthCanvaStartRouteImport } from './routes/api/oauth.canva.start'
import { Route as ApiOauthInstagramCallbackRouteImport } from './routes/api/oauth.instagram.callback'
import { Route as ApiOauthInstagramStartRouteImport } from './routes/api/oauth.instagram.start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const InspireRoute = InspireRouteImport.update({
  id: '/inspire',
  path: '/inspire',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsRoute,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => CampaignsRoute,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateRoute,
} as any)
const CreateImageRoute = CreateImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => CreateRoute,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioProjectIdRoute = StudioProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => StudioRoute,
} as any)
const ApiIgMediaIdRoute = ApiIgMediaIdRouteImport.update({
  id: '/api/ig-media/$id',
  path: '/api/ig-media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthCanvaCallbackRoute = ApiOauthCanvaCallbackRouteImport.update({
  id: '/api/oauth/canva/callback',
  path: '/api/oauth/canva/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthCanvaStartRoute = ApiOauthCanvaStartRouteImport.update({
  id: '/api/oauth/canva/start',
  path: '/api/oauth/canva/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthInstagramCallbackRoute =
  ApiOauthInstagramCallbackRouteImport.update({
    id: '/api/oauth/instagram/callback',
    path: '/api/oauth/instagram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthInstagramStartRoute = ApiOauthInstagramStartRouteImport.update({
  id: '/api/oauth/instagram/start',
  path: '/api/oauth/instagram/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/assistant': typeof AssistantRoute
  '/brand': typeof BrandRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/connect': typeof ConnectRoute
  '/create': typeof CreateRouteWithChildren
  '/export': typeof ExportRoute
  '/inspire': typeof InspireRoute
  '/instagram': typeof InstagramRoute
  '/studio': typeof StudioRouteWithChildren
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/create/image': typeof CreateImageRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/create/': typeof CreateIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/ig-media/$id': typeof ApiIgMediaIdRoute
  '/api/oauth/canva/callback': typeof ApiOauthCanvaCallbackRoute
  '/api/oauth/canva/start': typeof ApiOauthCanvaStartRoute
  '/api/oauth/instagram/callback': typeof ApiOauthInstagramCallbackRoute
  '/api/oauth/instagram/start': typeof ApiOauthInstagramStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/assistant': typeof AssistantRoute
  '/brand': typeof BrandRoute
  '/calendar': typeof CalendarRoute
  '/connect': typeof ConnectRoute
  '/export': typeof ExportRoute
  '/inspire': typeof InspireRoute
  '/instagram': typeof InstagramRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/create/image': typeof CreateImageRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/create': typeof CreateIndexRoute
  '/studio': typeof StudioIndexRoute
  '/api/ig-media/$id': typeof ApiIgMediaIdRoute
  '/api/oauth/canva/callback': typeof ApiOauthCanvaCallbackRoute
  '/api/oauth/canva/start': typeof ApiOauthCanvaStartRoute
  '/api/oauth/instagram/callback': typeof ApiOauthInstagramCallbackRoute
  '/api/oauth/instagram/start': typeof ApiOauthInstagramStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/assistant': typeof AssistantRoute
  '/brand': typeof BrandRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/connect': typeof ConnectRoute
  '/create': typeof CreateRouteWithChildren
  '/export': typeof ExportRoute
  '/inspire': typeof InspireRoute
  '/instagram': typeof InstagramRoute
  '/studio': typeof StudioRouteWithChildren
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/create/image': typeof CreateImageRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/create/': typeof CreateIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/ig-media/$id': typeof ApiIgMediaIdRoute
  '/api/oauth/canva/callback': typeof ApiOauthCanvaCallbackRoute
  '/api/oauth/canva/start': typeof ApiOauthCanvaStartRoute
  '/api/oauth/instagram/callback': typeof ApiOauthInstagramCallbackRoute
  '/api/oauth/instagram/start': typeof ApiOauthInstagramStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/assistant'
    | '/brand'
    | '/calendar'
    | '/campaigns'
    | '/connect'
    | '/create'
    | '/export'
    | '/inspire'
    | '/instagram'
    | '/studio'
    | '/campaigns/$campaignId'
    | '/create/image'
    | '/studio/$projectId'
    | '/campaigns/'
    | '/create/'
    | '/studio/'
    | '/api/ig-media/$id'
    | '/api/oauth/canva/callback'
    | '/api/oauth/canva/start'
    | '/api/oauth/instagram/callback'
    | '/api/oauth/instagram/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/assistant'
    | '/brand'
    | '/calendar'
    | '/connect'
    | '/export'
    | '/inspire'
    | '/instagram'
    | '/campaigns/$campaignId'
    | '/create/image'
    | '/studio/$projectId'
    | '/campaigns'
    | '/create'
    | '/studio'
    | '/api/ig-media/$id'
    | '/api/oauth/canva/callback'
    | '/api/oauth/canva/start'
    | '/api/oauth/instagram/callback'
    | '/api/oauth/instagram/start'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/assistant'
    | '/brand'
    | '/calendar'
    | '/campaigns'
    | '/connect'
    | '/create'
    | '/export'
    | '/inspire'
    | '/instagram'
    | '/studio'
    | '/campaigns/$campaignId'
    | '/create/image'
    | '/studio/$projectId'
    | '/campaigns/'
    | '/create/'
    | '/studio/'
    | '/api/ig-media/$id'
    | '/api/oauth/canva/callback'
    | '/api/oauth/canva/start'
    | '/api/oauth/instagram/callback'
    | '/api/oauth/instagram/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  AssistantRoute: typeof AssistantRoute
  BrandRoute: typeof BrandRoute
  CalendarRoute: typeof CalendarRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  CreateRoute: typeof CreateRouteWithChildren
  ExportRoute: typeof ExportRoute
  InspireRoute: typeof InspireRoute
  InstagramRoute: typeof InstagramRoute
  StudioRoute: typeof StudioRouteWithChildren
  ApiIgMediaIdRoute: typeof ApiIgMediaIdRoute
  ApiOauthCanvaCallbackRoute: typeof ApiOauthCanvaCallbackRoute
  ApiOauthCanvaStartRoute: typeof ApiOauthCanvaStartRoute
  ApiOauthInstagramCallbackRoute: typeof ApiOauthInstagramCallbackRoute
  ApiOauthInstagramStartRoute: typeof ApiOauthInstagramStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspire': {
      id: '/inspire'
      path: '/inspire'
      fullPath: '/inspire'
      preLoaderRoute: typeof InspireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/create/': {
      id: '/create/'
      path: '/'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/image': {
      id: '/create/image'
      path: '/image'
      fullPath: '/create/image'
      preLoaderRoute: typeof CreateImageRouteImport
      parentRoute: typeof CreateRoute
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$projectId': {
      id: '/studio/$projectId'
      path: '/$projectId'
      fullPath: '/studio/$projectId'
      preLoaderRoute: typeof StudioProjectIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/ig-media/$id': {
      id: '/api/ig-media/$id'
      path: '/api/ig-media/$id'
      fullPath: '/api/ig-media/$id'
      preLoaderRoute: typeof ApiIgMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/canva/callback': {
      id: '/api/oauth/canva/callback'
      path: '/api/oauth/canva/callback'
      fullPath: '/api/oauth/canva/callback'
      preLoaderRoute: typeof ApiOauthCanvaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/canva/start': {
      id: '/api/oauth/canva/start'
      path: '/api/oauth/canva/start'
      fullPath: '/api/oauth/canva/start'
      preLoaderRoute: typeof ApiOauthCanvaStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/instagram/callback': {
      id: '/api/oauth/instagram/callback'
      path: '/api/oauth/instagram/callback'
      fullPath: '/api/oauth/instagram/callback'
      preLoaderRoute: typeof ApiOauthInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/instagram/start': {
      id: '/api/oauth/instagram/start'
      path: '/api/oauth/instagram/start'
      fullPath: '/api/oauth/instagram/start'
      preLoaderRoute: typeof ApiOauthInstagramStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CampaignsRouteChildren {
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

interface CreateRouteChildren {
  CreateImageRoute: typeof CreateImageRoute
  CreateIndexRoute: typeof CreateIndexRoute
}

const CreateRouteChildren: CreateRouteChildren = {
  CreateImageRoute: CreateImageRoute,
  CreateIndexRoute: CreateIndexRoute,
}

const CreateRouteWithChildren =
  CreateRoute._addFileChildren(CreateRouteChildren)

interface StudioRouteChildren {
  StudioProjectIdRoute: typeof StudioProjectIdRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioProjectIdRoute: StudioProjectIdRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  AssistantRoute: AssistantRoute,
  BrandRoute: BrandRoute,
  CalendarRoute: CalendarRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  ConnectRoute: ConnectRoute,
  CreateRoute: CreateRouteWithChildren,
  ExportRoute: ExportRoute,
  InspireRoute: InspireRoute,
  InstagramRoute: InstagramRoute,
  StudioRoute: StudioRouteWithChildren,
  ApiIgMediaIdRoute: ApiIgMediaIdRoute,
  ApiOauthCanvaCallbackRoute: ApiOauthCanvaCallbackRoute,
  ApiOauthCanvaStartRoute: ApiOauthCanvaStartRoute,
  ApiOauthInstagramCallbackRoute: ApiOauthInstagramCallbackRoute,
  ApiOauthInstagramStartRoute: ApiOauthInstagramStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
