/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ExportRouteImport } from './routes/export'
import { Route as IgRouteImport } from './routes/ig'
import { Route as InspireRouteImport } from './routes/inspire'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioProjectIdRouteImport } from './routes/studio.$projectId'
import { Route as ApiConnectSplatRouteImport } from './routes/api/connect.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const IgRoute = IgRouteImport.update({
  id: '/ig',
  path: '/ig',
  getParentRoute: () => rootRouteImport,
} as any)
const InspireRoute = InspireRouteImport.update({
  id: '/inspire',
  path: '/inspire',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsRoute,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => CampaignsRoute,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioProjectIdRoute = StudioProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => StudioRoute,
} as any)
const ApiConnectSplatRoute = ApiConnectSplatRouteImport.update({
  id: '/api/connect/$',
  path: '/api/connect/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/assistant': typeof AssistantRoute
  '/brand': typeof BrandRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/connect': typeof ConnectRoute
  '/create': typeof CreateRoute
  '/export': typeof ExportRoute
  '/ig': typeof IgRoute
  '/inspire': typeof InspireRoute
  '/studio': typeof StudioRouteWithChildren
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/studio/': typeof StudioIndexRoute
  '/api/connect/$': typeof ApiConnectSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/assistant': typeof AssistantRoute
  '/brand': typeof BrandRoute
  '/calendar': typeof CalendarRoute
  '/connect': typeof ConnectRoute
  '/create': typeof CreateRoute
  '/export': typeof ExportRoute
  '/ig': typeof IgRoute
  '/inspire': typeof InspireRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/studio': typeof StudioIndexRoute
  '/api/connect/$': typeof ApiConnectSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/assistant': typeof AssistantRoute
  '/brand': typeof BrandRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/connect': typeof ConnectRoute
  '/create': typeof CreateRoute
  '/export': typeof ExportRoute
  '/ig': typeof IgRoute
  '/inspire': typeof InspireRoute
  '/studio': typeof StudioRouteWithChildren
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/studio/': typeof StudioIndexRoute
  '/api/connect/$': typeof ApiConnectSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/assistant'
    | '/brand'
    | '/calendar'
    | '/campaigns'
    | '/connect'
    | '/create'
    | '/export'
    | '/ig'
    | '/inspire'
    | '/studio'
    | '/campaigns/$campaignId'
    | '/studio/$projectId'
    | '/studio/'
    | '/api/connect/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/assistant'
    | '/brand'
    | '/calendar'
    | '/connect'
    | '/create'
    | '/export'
    | '/ig'
    | '/inspire'
    | '/campaigns/$campaignId'
    | '/studio/$projectId'
    | '/studio'
    | '/api/connect/$'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/assistant'
    | '/brand'
    | '/calendar'
    | '/campaigns'
    | '/connect'
    | '/create'
    | '/export'
    | '/ig'
    | '/inspire'
    | '/studio'
    | '/campaigns/$campaignId'
    | '/studio/$projectId'
    | '/studio/'
    | '/api/connect/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  AssistantRoute: typeof AssistantRoute
  BrandRoute: typeof BrandRoute
  CalendarRoute: typeof CalendarRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  CreateRoute: typeof CreateRoute
  ExportRoute: typeof ExportRoute
  IgRoute: typeof IgRoute
  InspireRoute: typeof InspireRoute
  StudioRoute: typeof StudioRouteWithChildren
  ApiConnectSplatRoute: typeof ApiConnectSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ig': {
      id: '/ig'
      path: '/ig'
      fullPath: '/ig'
      preLoaderRoute: typeof IgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspire': {
      id: '/inspire'
      path: '/inspire'
      fullPath: '/inspire'
      preLoaderRoute: typeof InspireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$projectId': {
      id: '/studio/$projectId'
      path: '/$projectId'
      fullPath: '/studio/$projectId'
      preLoaderRoute: typeof StudioProjectIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/connect/$': {
      id: '/api/connect/$'
      path: '/api/connect/$'
      fullPath: '/api/connect/$'
      preLoaderRoute: typeof ApiConnectSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioProjectIdRoute: typeof StudioProjectIdRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioProjectIdRoute: StudioProjectIdRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  AssistantRoute: AssistantRoute,
  BrandRoute: BrandRoute,
  CalendarRoute: CalendarRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  ConnectRoute: ConnectRoute,
  CreateRoute: CreateRoute,
  ExportRoute: ExportRoute,
  IgRoute: IgRoute,
  InspireRoute: InspireRoute,
  StudioRoute: StudioRouteWithChildren,
  ApiConnectSplatRoute: ApiConnectSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
