import {
  SEED_CAMPUS_ID,
  SEED_LIGHT_ID,
  SEED_LOGO_ID,
  SEED_TEA_ID,
  SEED_TURTLE_ID,
  SEED_TAMSUI_ID,
} from "../studio/seed-ids.ts";
import type {
  ClubCampaign,
  ConnectionState,
  IgMemoryPost,
  Inspiration,
  MemoryItem,
} from "./types.ts";

export const SEED_CAMPAIGN_ID = "camp_float_light";

export const SEED_CONNECTIONS: ConnectionState[] = [
  {
    id: "google-drive",
    status: "memory",
    accountLabel: "淡江禪學社資料夾",
    folderHint: "尚未授權官方 Drive，先用社團 Creative Memory",
    lastSyncAt: Date.parse("2026-09-12T09:00:00+08:00"),
  },
  {
    id: "canva",
    status: "memory",
    accountLabel: "禪學社 Canva",
    folderHint: "尚未授權官方 Canva，先用歷屆設計記憶",
    lastSyncAt: Date.parse("2026-09-12T09:00:00+08:00"),
  },
  {
    id: "instagram",
    status: "memory",
    accountLabel: "@tkuzen",
    folderHint: "尚未授權官方 IG，先用內容記憶",
    lastSyncAt: Date.parse("2026-09-15T21:00:00+08:00"),
  },
];

export const SEED_CAMPAIGNS: ClubCampaign[] = [
  {
    id: SEED_CAMPAIGN_ID,
    name: "浮游禪光",
    type: "light",
    date: "2026-09-24",
    time: "19:30",
    location: "淡江大學 覺生紀念圖書館前",
    oneLiner: "一個不用表演的晚上。",
    fullIntro:
      "開學以後大家都在趕。浮游禪光用燈光和熱茶，讓淡江學生可以坐下來。不用先懂禪，也不用分享心事。",
    theme: "坐下來",
    studentPain: "連休息都有罪惡感；剛到淡水還沒找到自己的晚上。",
    cta: "晚上來坐一下",
    signupUrl: "",
    coverAssetId: SEED_LIGHT_ID,
    relatedAssetIds: [SEED_LIGHT_ID, SEED_TEA_ID, SEED_TURTLE_ID, SEED_LOGO_ID],
    projectIds: ["proj_float_light"],
    waves: [
      {
        id: "wave_emotion",
        offsetDays: -10,
        intent: "情緒共鳴",
        topic: "很久沒坐好",
        contentKind: "ig-post",
        projectId: null,
        scheduledAt: Date.parse("2026-09-14T20:00:00+08:00"),
        status: "published",
      },
      {
        id: "wave_visual",
        offsetDays: -7,
        intent: "主視覺",
        topic: "浮游禪光 Carousel",
        contentKind: "carousel",
        projectId: "proj_float_light",
        scheduledAt: Date.parse("2026-09-17T19:00:00+08:00"),
        status: "scheduled",
      },
      {
        id: "wave_reason",
        offsetDays: -5,
        intent: "參加理由",
        topic: "帶一個朋友就好",
        contentKind: "story",
        projectId: null,
        scheduledAt: Date.parse("2026-09-19T21:00:00+08:00"),
        status: "idea",
      },
      {
        id: "wave_count",
        offsetDays: -1,
        intent: "倒數",
        topic: "明天晚上圖書館前",
        contentKind: "countdown",
        projectId: null,
        scheduledAt: Date.parse("2026-09-23T18:00:00+08:00"),
        status: "idea",
      },
      {
        id: "wave_day",
        offsetDays: 0,
        intent: "當天提醒",
        topic: "今天 19:30",
        contentKind: "story",
        projectId: null,
        scheduledAt: Date.parse("2026-09-24T12:00:00+08:00"),
        status: "idea",
      },
      {
        id: "wave_recap",
        offsetDays: 1,
        intent: "活動回顧",
        topic: "昨天有人真的坐下來了",
        contentKind: "recap",
        projectId: null,
        scheduledAt: Date.parse("2026-09-25T12:00:00+08:00"),
        status: "idea",
      },
    ],
    createdAt: Date.parse("2026-09-10T20:00:00+08:00"),
    updatedAt: Date.parse("2026-09-15T10:00:00+08:00"),
  },
];

export const SEED_MEMORY: MemoryItem[] = [
  {
    id: "mem_drive_tea_2025",
    source: "drive",
    sourceLabel: "Google Drive / 2025 茶會",
    title: "夜間茶會現場照片",
    kind: "photo",
    tags: ["茶會", "晚上", "同學互動", "杯子"],
    assetId: SEED_TEA_ID,
    summary: "很多人圍坐，燈光偏暖，適合當生活感主視覺。",
    createdAt: Date.parse("2025-10-08T20:00:00+08:00"),
  },
  {
    id: "mem_drive_float_copy",
    source: "drive",
    sourceLabel: "Google Drive / 浮游禪光文宣",
    title: "浮游禪光企劃摘要",
    kind: "doc",
    tags: ["浮游禪光", "文宣", "夜間"],
    assetId: SEED_LIGHT_ID,
    summary: "主題是光與坐下，不是講經。",
    createdAt: Date.parse("2026-08-20T10:00:00+08:00"),
  },
  {
    id: "mem_drive_turtle",
    source: "drive",
    sourceLabel: "Google Drive / 角色",
    title: "龜龜素材",
    kind: "logo",
    tags: ["龜龜", "吉祥物"],
    assetId: SEED_TURTLE_ID,
    summary: "圓背、三色甲，可當配角不要當宗教圖騰。",
    createdAt: Date.parse("2025-03-01T10:00:00+08:00"),
  },
  {
    id: "mem_drive_campus",
    source: "drive",
    sourceLabel: "Google Drive / 場地",
    title: "校園小路與圖書館",
    kind: "photo",
    tags: ["淡江校園", "場地", "圖書館"],
    assetId: SEED_CAMPUS_ID,
    summary: "適合證明「就在學校」。",
    createdAt: Date.parse("2025-09-12T16:00:00+08:00"),
  },
  {
    id: "mem_canva_tea",
    source: "canva",
    sourceLabel: "Canva / 茶會海報",
    title: "歷屆茶會主視覺",
    kind: "design",
    tags: ["茶會", "海報", "招生版型"],
    assetId: SEED_TEA_ID,
    summary: "上半照片、下半時間地點。留白夠，字級大。",
    createdAt: Date.parse("2025-09-30T14:00:00+08:00"),
  },
  {
    id: "mem_canva_light",
    source: "canva",
    sourceLabel: "Canva / 浮游禪光",
    title: "三色光夜間版型",
    kind: "design",
    tags: ["三色光", "Story", "浮游禪光"],
    assetId: SEED_LIGHT_ID,
    summary: "深底三色光，標題短。可延續不要複製。",
    createdAt: Date.parse("2026-08-28T18:00:00+08:00"),
  },
  {
    id: "mem_canva_recruit",
    source: "canva",
    sourceLabel: "Canva / 招生",
    title: "招生活動 Carousel 版型",
    kind: "design",
    tags: ["招生", "Carousel", "版型"],
    assetId: SEED_TURTLE_ID,
    summary: "Hook → 生活 → 我們在做什麼 → CTA。避免社團簡介開頭。",
    createdAt: Date.parse("2026-02-12T11:00:00+08:00"),
  },
  {
    id: "mem_ig_tea",
    source: "instagram",
    sourceLabel: "Instagram / 2025-09-18",
    title: "去年開學茶會",
    kind: "post",
    tags: ["茶會", "開學", "互動"],
    assetId: SEED_TEA_ID,
    summary: "生活口吻、收藏數較高。",
    createdAt: Date.parse("2025-09-18T19:00:00+08:00"),
  },
  {
    id: "mem_ig_turtle",
    source: "instagram",
    sourceLabel: "Instagram / 龜龜日常",
    title: "龜龜出沒",
    kind: "post",
    tags: ["龜龜", "日常"],
    assetId: SEED_TURTLE_ID,
    summary: "輕、短、學生會停。不是活動廣告。",
    createdAt: Date.parse("2026-03-04T12:00:00+08:00"),
  },
  {
    id: "mem_tamsui",
    source: "drive",
    sourceLabel: "Google Drive / 淡水",
    title: "淡水黃昏河岸",
    kind: "photo",
    tags: ["淡水", "黃昏", "通勤"],
    assetId: SEED_TAMSUI_ID,
    summary: "適合通勤生情緒文。",
    createdAt: Date.parse("2026-04-02T18:30:00+08:00"),
  },
];

export const SEED_IG_POSTS: IgMemoryPost[] = [
  {
    id: "ig_20250918",
    source: "seed",
    mediaType: "carousel",
    caption:
      "開學第一週，有人課表還沒齊。\n我們先泡茶。不用自我介紹得很完整，坐下來就好。",
    takenAt: Date.parse("2025-09-18T19:12:00+08:00"),
    assetIds: [SEED_TEA_ID, SEED_TURTLE_ID],
    likes: 186,
    comments: 14,
    saves: 41,
    reach: 2400,
    analysis: {
      hook: "開學第一週，有人課表還沒齊。",
      visual: "茶會圍坐，生活感強",
      theme: "開學適應",
      captionLength: 42,
      cta: "坐下來就好",
      direction: "生活入口，活動只在後面",
      improve: ["時間地點可以更早出現", "最後一頁 CTA 再大一點"],
    },
  },
  {
    id: "ig_20260304",
    source: "seed",
    mediaType: "image",
    caption: "龜龜今天也在。\n你今天有真的休息嗎。",
    takenAt: Date.parse("2026-03-04T12:04:00+08:00"),
    assetIds: [SEED_TURTLE_ID],
    likes: 254,
    comments: 31,
    saves: 67,
    reach: 3100,
    analysis: {
      hook: "你今天有真的休息嗎。",
      visual: "角色特寫，停留感高",
      theme: "日常／龜龜",
      captionLength: 18,
      cta: "無硬 CTA",
      direction: "短句＋角色，不是招生",
      improve: ["可做系列，不要連續改成活動文"],
    },
  },
  {
    id: "ig_20260512",
    source: "seed",
    mediaType: "image",
    caption: "期末不是要你更努力。\n有時候只是需要一個不說話的角落。",
    takenAt: Date.parse("2026-05-12T21:08:00+08:00"),
    assetIds: [SEED_TAMSUI_ID],
    likes: 201,
    comments: 9,
    saves: 88,
    reach: 2700,
    analysis: {
      hook: "期末不是要你更努力。",
      visual: "淡水黃昏，情緒停留",
      theme: "期末陪伴",
      captionLength: 28,
      cta: "無",
      direction: "陪伴型，收藏高",
      improve: ["若要導流，可在限動補時間"],
    },
  },
  {
    id: "ig_20260830",
    source: "seed",
    mediaType: "reels",
    caption: "還在淡水的人，晚上風開始涼了。",
    takenAt: Date.parse("2026-08-30T18:40:00+08:00"),
    assetIds: [SEED_LIGHT_ID],
    likes: 142,
    comments: 6,
    saves: 22,
    reach: 1900,
    analysis: {
      hook: "晚上風開始涼了。",
      visual: "光斑，適合 Reels 封面",
      theme: "開學前生活",
      captionLength: 16,
      cta: "無",
      direction: "氛圍先行",
      improve: ["封面字再少兩個"],
    },
  },
];

export const SEED_INSPIRATION: Inspiration[] = [
  {
    id: "insp_carousel_hook",
    title: "校園 Carousel 停留",
    pattern: "第一頁只留一句生活問句",
    composition: "上半滿版、下半大字",
    color: "低飽和＋一點光",
    hookShape: "問句，不講社團名",
    form: "5–6 頁，第三頁才出現活動",
    clubTurn: "用淡江課表／捷運當第一句，而不是禪學社簡介。",
  },
  {
    id: "insp_reels_cover",
    title: "Reels 封面少字",
    pattern: "封面 ≤ 8 字",
    composition: "臉或光在中上，字靠下安全區",
    color: "夜間對比",
    hookShape: "口語短句",
    form: "0–3 秒先對到生活",
    clubTurn: "封面寫「很久沒坐好」，不要寫活動全名。",
  },
  {
    id: "insp_mix_rhythm",
    title: "帳號節奏不要連發招生",
    pattern: "宣傳中間穿生活與互動",
    composition: "一則活動、一則生活、一則提問",
    color: "活動用夜間光，生活用霧亞麻",
    hookShape: "生活句與活動句輪替",
    form: "週曆：情緒 → 主視覺 → 知識／故事 → 倒數",
    clubTurn: "浮游禪光週不要連發三則報名。星期二生活，星期四主視覺，星期六倒數。",
  },
];
